version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
      - POSTGRES_DB=fw_database
    ports:
      - "5432:5432"

  migration-runner:
    build:
      context: ./database/migrations
      dockerfile: Dockerfile
    container_name: migration-runner
    entrypoint: [ "/bin/sh", "-c", "echo 'MIGRATION-RUNNER START!' && sleep 3 && goose -dir /tmp/migrations postgres 'host=postgres port=5432 user=local_user password=local_pass dbname=fw_database sslmode=disable' up && echo 'MIGRATION-RUNNER DONE!' && sleep 1" ]
    volumes:
      - ./database/migrations:/tmp/migrations
    depends_on:
      - postgres