version: '3.8'
services:
  postgres-local:
    container_name: postgres-local
    image: postgres:latest
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_pass
      - POSTGRES_DB=fw_database
    ports:
      - "5432:5432"
    networks:
      - country-service-network

networks:
  country-service-network:
    driver: bridge
