version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_database_name
    ports:
      - "5432:5432"

  migration-runner:
    image: golang:1.20.5-alpine3.18
    container_name: migration-runner
    entrypoint: [ "/bin/sh", "-c", "go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir /tmp/migrations postgres 'host=postgres port=5432 user=your_postgres_user password=your_postgres_password dbname=your_database_name sslmode=disable' up && echo 'MIGRATION-RUNNER DONE!' && sleep 20"]
    volumes:
      - ./database/migrations:/tmp/migrations
    depends_on:
      - postgres


